version: "2"
services:
  bridge:
    build: ./bridge-server
    ports:
      - "8001:8001"
    command: ./wait-for-it.sh bridge-db:3306 -t 600 -s -- ./bridge
    depends_on:
      - bridge-db
    container_name: bridge
  bridge-db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: bridge
      MYSQL_DATABASE: bridge
      MYSQL_USER: bridge
      MYSQL_PASSWORD: bridge
      TZ: JST
    volumes:
      - ./bridge-db/conf.d:/etc/mysql/conf.d
      - bridge-db-data:/var/lib/mysql
    container_name: bridge-db
  federation-kumano-te.com:
    build: ./federation-server
    ports:
      - "8002:8002"
    command: ./wait-for-it.sh federation-db:3306 -t 600 -s -- ./federation
    depends_on:
      - federation-db
    container_name: federation-kumano-te.com
  federation-db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: federation
      MYSQL_DATABASE: federation
      MYSQL_USER: federation
      MYSQL_PASSWORD: federation
      TZ: JST
    volumes:
      - ./federation-db/init.d:/docker-entrypoint-initdb.d
      - ./federation-db/conf.d:/etc/mysql/conf.d
      - federation-db-data:/var/lib/mysql
    container_name: federation-db
  compliance-kumano-te.com:
    build: ./compliance-server
    ports:
      - "8003:8003"
      - "8004:8004"
    command: ./wait-for-it.sh compliance-db:3306 -t 600 -s -- ./compliance
    depends_on:
      - compliance-db
    container_name: compliance-kumano-te.com
  compliance-db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: compliance
      MYSQL_DATABASE: compliance
      MYSQL_USER: compliance
      MYSQL_PASSWORD: compliance
      TZ: JST
    volumes:
      - ./compliance-db/conf.d:/etc/mysql/conf.d
      - compliance-db-data:/var/lib/mysql
    container_name: compliance-db
volumes:
  bridge-db-data:
    driver: local
  federation-db-data:
    driver: local
  compliance-db-data:
    driver: local
